### Deliverable 1: Preprocessing the Data for a Neural Network

In [1]:
# Import our dependencies
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler,OneHotEncoder
import pandas as pd
import tensorflow as tf

#  Import and read the charity_data.csv.
import pandas as pd 
application_df = pd.read_csv("Resources/charity_data.csv")
application_df.head()

,EIN,NAME,APPLICATION_TYPE,AFFILIATION,CLASSIFICATION,USE_CASE,ORGANIZATION,STATUS,INCOME_AMT,SPECIAL_CONSIDERATIONS,ASK_AMT,IS_SUCCESSFUL
0,10520599,BLUE KNIGHTS MOTORCYCLE CLUB,T10,Independent,C1000,ProductDev,Association,1,0,N,5000,1
1,10531628,AMERICAN CHESAPEAKE CLUB CHARITABLE TR,T3,Independent,C2000,Preservation,Co-operative,1,1-9999,N,108590,1
2,10547893,ST CLOUD PROFESSIONAL FIREFIGHTERS,T5,CompanySponsored,C3000,ProductDev,Association,1,0,N,5000,0
3,10553066,SOUTHSIDE ATHLETIC ASSOCIATION,T3,CompanySponsored,C2000,Preservation,Trust,1,10000-24999,N,6692,1
4,10556103,GENETIC RESEARCH INSTITUTE OF THE DESERT,T3,Independent,C1000,Heathcare,Trust,1,100000-499999,N,142590,1

In [2]:
# Drop the non-beneficial ID columns, 'EIN' and 'NAME'.
#  YOUR CODE GOES HERE
application_df = application_df.drop(['EIN', 'NAME', 'USE_CASE', 'CLASSIFICATION', 'APPLICATION_TYPE'], 1)
application_df.head(10)

,AFFILIATION,ORGANIZATION,STATUS,INCOME_AMT,SPECIAL_CONSIDERATIONS,ASK_AMT,IS_SUCCESSFUL
0,Independent,Association,1,0,N,5000,1
1,Independent,Co-operative,1,1-9999,N,108590,1
2,CompanySponsored,Association,1,0,N,5000,0
3,CompanySponsored,Trust,1,10000-24999,N,6692,1
4,Independent,Trust,1,100000-499999,N,142590,1
5,Independent,Trust,1,0,N,5000,1
6,Independent,Trust,1,100000-499999,N,31452,1
7,Independent,Trust,1,10M-50M,N,7508025,1
8,Independent,Trust,1,1-9999,N,94389,1
9,CompanySponsored,Association,1,0,N,5000,0

In [3]:
# Determine the number of unique values in each column.
#  YOUR CODE GOES HERE
application_cat = application_df.dtypes[application_df.dtypes == "object"].index.tolist()
# application_cat
application_df.nunique()

AFFILIATION                  6
ORGANIZATION                 4
STATUS                       2
INCOME_AMT                   9
SPECIAL_CONSIDERATIONS       2
ASK_AMT                   8747
IS_SUCCESSFUL                2
dtype: int64

In [4]:
# ask_counts = application_df.ASK_AMT.value_counts()
# application_df['ASK_AMT'].sort_values(ascending=False)

In [5]:
# application_df['ASK_AMT'].describe()

In [6]:
# # Look at APPLICATION_TYPE value counts for binning
# #  YOUR CODE GOES HERE
# type_counts = application_df.APPLICATION_TYPE.value_counts()
# type_counts

In [7]:
# # Visualize the value counts of APPLICATION_TYPE
# #  YOUR CODE GOES HERE
# type_counts.plot.density()

In [8]:
# # Determine which values to replace if counts are less than ...?
# #  YOUR CODE GOES HERE
# replace_application = list(type_counts[type_counts < 200].index)

# # Replace in dataframe
# for app in replace_application:
#     application_df.APPLICATION_TYPE = application_df.APPLICATION_TYPE.replace(app,"Other")
    
# # Check to make sure binning was successful
# application_df.APPLICATION_TYPE.value_counts()

In [9]:
# # Look at CLASSIFICATION value counts for binning
# #  YOUR CODE GOES HERE
# class_counts = application_df.CLASSIFICATION.value_counts()
# class_counts

In [10]:
# # Visualize the value counts of CLASSIFICATION
# #  YOUR CODE GOES HERE
# class_counts.plot.density()

In [11]:
# # Determine which values to replace if counts are less than ..?
# #  YOUR CODE GOES HERE
# replace_class = list(class_counts[class_counts < 1500].index)

# # Replace in dataframe
# for cls in replace_class:
#     application_df.CLASSIFICATION = application_df.CLASSIFICATION.replace(cls,"Other")
    
# # Check to make sure binning was successful
# application_df.CLASSIFICATION.value_counts()

In [12]:
# Generate our categorical variable lists
#  YOUR CODE GOES HERE
application_cat = application_df.dtypes[application_df.dtypes == "object"].index.tolist()

In [13]:
# Create a OneHotEncoder instance
enc = OneHotEncoder(sparse=False)

# Fit and transform the OneHotEncoder using the categorical variable list
#  YOUR CODE GOES HERE
encode_df = pd.DataFrame(enc.fit_transform(application_df[application_cat]))


# Add the encoded variable names to the dataframe
encode_df.columns = enc.get_feature_names(application_cat)
encode_df.head()

,AFFILIATION_CompanySponsored,AFFILIATION_Family/Parent,AFFILIATION_Independent,AFFILIATION_National,AFFILIATION_Other,AFFILIATION_Regional,ORGANIZATION_Association,ORGANIZATION_Co-operative,ORGANIZATION_Corporation,ORGANIZATION_Trust,...,INCOME_AMT_1-9999,INCOME_AMT_10000-24999,INCOME_AMT_100000-499999,INCOME_AMT_10M-50M,INCOME_AMT_1M-5M,INCOME_AMT_25000-99999,INCOME_AMT_50M+,INCOME_AMT_5M-10M,SPECIAL_CONSIDERATIONS_N,SPECIAL_CONSIDERATIONS_Y
0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
1,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
2,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
3,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
4,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0

In [14]:
# Merge one-hot encoded features and drop the originals
#  YOUR CODE GOES HERE
application_df = application_df.merge(encode_df,left_index=True, right_index=True)
application_df = application_df.drop(application_cat,1)
application_df.head()

,STATUS,ASK_AMT,IS_SUCCESSFUL,AFFILIATION_CompanySponsored,AFFILIATION_Family/Parent,AFFILIATION_Independent,AFFILIATION_National,AFFILIATION_Other,AFFILIATION_Regional,ORGANIZATION_Association,...,INCOME_AMT_1-9999,INCOME_AMT_10000-24999,INCOME_AMT_100000-499999,INCOME_AMT_10M-50M,INCOME_AMT_1M-5M,INCOME_AMT_25000-99999,INCOME_AMT_50M+,INCOME_AMT_5M-10M,SPECIAL_CONSIDERATIONS_N,SPECIAL_CONSIDERATIONS_Y
0,1,5000,1,0.0,0.0,1.0,0.0,0.0,0.0,1.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
1,1,108590,1,0.0,0.0,1.0,0.0,0.0,0.0,0.0,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
2,1,5000,0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
3,1,6692,1,1.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
4,1,142590,1,0.0,0.0,1.0,0.0,0.0,0.0,0.0,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0

In [15]:
# Split our preprocessed data into our features and target arrays
y = application_df["IS_SUCCESSFUL"].values
X = application_df.drop(["IS_SUCCESSFUL"],1).values

# Split the preprocessed data into a training and testing dataset
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=78)

In [16]:
# Create a StandardScaler instances
scaler = StandardScaler()

# Fit the StandardScaler
X_scaler = scaler.fit(X_train)

# Scale the data
X_train_scaled = X_scaler.transform(X_train)
X_test_scaled = X_scaler.transform(X_test)

### Deliverable 2: Compile, Train and Evaluate the Model

In [17]:
# Define the model - deep neural net, i.e., the number of input features and hidden nodes for each layer.
#  YOUR CODE GOES HERE

number_input_features = len(X_train[0])
hidden_nodes_layer1 = 50
hidden_nodes_layer2 = 25


nn = tf.keras.models.Sequential()

# First hidden layer
nn.add(
    tf.keras.layers.Dense(units=hidden_nodes_layer1, input_dim=number_input_features, activation="relu")
)

# Second hidden layer
nn.add(tf.keras.layers.Dense(units=hidden_nodes_layer2, activation="relu"))


# Output layer
nn.add(tf.keras.layers.Dense(units=1, activation="sigmoid"))

# Check the structure of the model
nn.summary()

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #
=================================================================
dense (Dense)                (None, 50)                1200
_________________________________________________________________
dense_1 (Dense)              (None, 25)                1275
_________________________________________________________________
dense_2 (Dense)              (None, 1)                 26
=================================================================
Total params: 2,501
Trainable params: 2,501
Non-trainable params: 0
_________________________________________________________________

In [18]:
# Compile the model
#  YOUR CODE GOES HERE
nn.compile(loss="binary_crossentropy", optimizer="adam", metrics=["accuracy"])

In [19]:
# Create a callback that saves the model's weights every five epochs
# Import checkpoint dependencies
import os
from tensorflow.keras.callbacks import ModelCheckpoint

# Define the checkpoint path and filenames
os.makedirs("checkpoints/",exist_ok=True)
checkpoint_path = "checkpoints/weights.{epoch:02d}.hdf5"

cp_callback = ModelCheckpoint(
    filepath=checkpoint_path,
    verbose=1,
    save_weights_only=True,
    save_freq=4020)
#     ,
#     period=5)

In [20]:
# Train the model
#  YOUR CODE GOES HERE
fit_model = nn.fit(X_train,y_train,epochs=100, callbacks=[cp_callback])

Epoch 1/100
804/804 [==============================] - 1s 752us/step - loss: 17097.6973 - accuracy: 0.4930
Epoch 2/100
804/804 [==============================] - 1s 895us/step - loss: 49500.9453 - accuracy: 0.5005
Epoch 3/100
804/804 [==============================] - 1s 920us/step - loss: 7953.9307 - accuracy: 0.4969
Epoch 4/100
804/804 [==============================] - 1s 761us/step - loss: 55417.2539 - accuracy: 0.4896
Epoch 5/100
792/804 [============================>.] - ETA: 0s - loss: 21856.2051 - accuracy: 0.4987
Epoch 00005: saving model to checkpoints/weights.05.hdf5
804/804 [==============================] - 1s 777us/step - loss: 21549.9902 - accuracy: 0.4991
Epoch 6/100
804/804 [==============================] - 1s 754us/step - loss: 20367.1660 - accuracy: 0.5100
Epoch 7/100
804/804 [==============================] - 1s 758us/step - loss: 7606.3120 - accuracy: 0.5122
Epoch 8/100
804/804 [==============================] - 1s 774us/step - loss: 20757.5078 - accuracy: 0.5105
Epoch 9/100
804/804 [==============================] - 1s 759us/step - loss: 12524.9531 - accuracy: 0.5051
Epoch 10/100
792/804 [============================>.] - ETA: 0s - loss: 5722.0581 - accuracy: 0.5027
Epoch 00010: saving model to checkpoints/weights.10.hdf5
804/804 [==============================] - 1s 770us/step - loss: 5644.2764 - accuracy: 0.5038
Epoch 11/100
804/804 [==============================] - 1s 792us/step - loss: 14686.2754 - accuracy: 0.5009
Epoch 12/100
804/804 [==============================] - 1s 802us/step - loss: 8886.6074 - accuracy: 0.5003
Epoch 13/100
804/804 [==============================] - 1s 757us/step - loss: 1605.8179 - accuracy: 0.5285
Epoch 14/100
804/804 [==============================] - 1s 774us/step - loss: 11596.0078 - accuracy: 0.5100
Epoch 15/100
790/804 [============================>.] - ETA: 0s - loss: 4596.4277 - accuracy: 0.5084
Epoch 00015: saving model to checkpoints/weights.15.hdf5
804/804 [==============================] - 1s 775us/step - loss: 4519.7646 - accuracy: 0.5083
Epoch 16/100
804/804 [==============================] - 1s 781us/step - loss: 3776.0598 - accuracy: 0.5110
Epoch 17/100
804/804 [==============================] - 1s 769us/step - loss: 2923.5398 - accuracy: 0.5154
Epoch 18/100
804/804 [==============================] - 1s 772us/step - loss: 39.4629 - accuracy: 0.5320
Epoch 19/100
804/804 [==============================] - 1s 778us/step - loss: 0.7079 - accuracy: 0.5322
Epoch 20/100
771/804 [===========================>..] - ETA: 0s - loss: 0.6931 - accuracy: 0.5323
Epoch 00020: saving model to checkpoints/weights.20.hdf5
804/804 [==============================] - 1s 792us/step - loss: 0.6931 - accuracy: 0.5321
Epoch 21/100
804/804 [==============================] - 1s 776us/step - loss: 0.6913 - accuracy: 0.5321
Epoch 22/100
804/804 [==============================] - 1s 773us/step - loss: 0.6911 - accuracy: 0.5321
Epoch 23/100
804/804 [==============================] - 1s 775us/step - loss: 0.6911 - accuracy: 0.5321
Epoch 24/100
804/804 [==============================] - 1s 774us/step - loss: 0.6911 - accuracy: 0.5321
Epoch 25/100
781/804 [============================>.] - ETA: 0s - loss: 0.6911 - accuracy: 0.5323
Epoch 00025: saving model to checkpoints/weights.25.hdf5
804/804 [==============================] - 1s 783us/step - loss: 0.6911 - accuracy: 0.5321
Epoch 26/100
804/804 [==============================] - 1s 782us/step - loss: 0.6911 - accuracy: 0.5321
Epoch 27/100
804/804 [==============================] - 1s 775us/step - loss: 0.6911 - accuracy: 0.5321
Epoch 28/100
804/804 [==============================] - 1s 777us/step - loss: 0.6911 - accuracy: 0.5321
Epoch 29/100
804/804 [==============================] - 1s 776us/step - loss: 0.6911 - accuracy: 0.5321
Epoch 30/100
786/804 [============================>.] - ETA: 0s - loss: 0.6911 - accuracy: 0.5319
Epoch 00030: saving model to checkpoints/weights.30.hdf5
804/804 [==============================] - 1s 778us/step - loss: 0.6911 - accuracy: 0.5321
Epoch 31/100
804/804 [==============================] - 1s 786us/step - loss: 0.6911 - accuracy: 0.5321
Epoch 32/100
804/804 [==============================] - 1s 759us/step - loss: 0.6911 - accuracy: 0.5321
Epoch 33/100
804/804 [==============================] - 1s 896us/step - loss: 0.6911 - accuracy: 0.5321
Epoch 34/100
804/804 [==============================] - 1s 859us/step - loss: 0.6911 - accuracy: 0.5321
Epoch 35/100
769/804 [===========================>..] - ETA: 0s - loss: 0.6912 - accuracy: 0.5317
Epoch 00035: saving model to checkpoints/weights.35.hdf5
804/804 [==============================] - 1s 1ms/step - loss: 0.6911 - accuracy: 0.5321
Epoch 36/100
804/804 [==============================] - 1s 1ms/step - loss: 0.6911 - accuracy: 0.5321
Epoch 37/100
804/804 [==============================] - 1s 852us/step - loss: 0.6911 - accuracy: 0.5321
Epoch 38/100
804/804 [==============================] - 1s 842us/step - loss: 0.6911 - accuracy: 0.5321
Epoch 39/100
804/804 [==============================] - 1s 851us/step - loss: 0.6911 - accuracy: 0.5321
Epoch 40/100
782/804 [============================>.] - ETA: 0s - loss: 0.6911 - accuracy: 0.5326
Epoch 00040: saving model to checkpoints/weights.40.hdf5
804/804 [==============================] - 1s 848us/step - loss: 0.6911 - accuracy: 0.5321
Epoch 41/100
804/804 [==============================] - 1s 875us/step - loss: 0.6911 - accuracy: 0.5321
Epoch 42/100
804/804 [==============================] - 1s 879us/step - loss: 0.6911 - accuracy: 0.5321
Epoch 43/100
804/804 [==============================] - 1s 889us/step - loss: 0.6911 - accuracy: 0.5321
Epoch 44/100
804/804 [==============================] - 1s 895us/step - loss: 0.6911 - accuracy: 0.5321
Epoch 45/100
763/804 [===========================>..] - ETA: 0s - loss: 0.6912 - accuracy: 0.5318
Epoch 00045: saving model to checkpoints/weights.45.hdf5
804/804 [==============================] - 1s 1ms/step - loss: 0.6911 - accuracy: 0.5321
Epoch 46/100
804/804 [==============================] - 1s 946us/step - loss: 0.6911 - accuracy: 0.5321
Epoch 47/100
804/804 [==============================] - 1s 823us/step - loss: 0.6911 - accuracy: 0.5321
Epoch 48/100
804/804 [==============================] - 1s 945us/step - loss: 0.6911 - accuracy: 0.5321
Epoch 49/100
804/804 [==============================] - 1s 858us/step - loss: 0.6911 - accuracy: 0.5321
Epoch 50/100
752/804 [===========================>..] - ETA: 0s - loss: 0.6912 - accuracy: 0.5316
Epoch 00050: saving model to checkpoints/weights.50.hdf5
804/804 [==============================] - 1s 946us/step - loss: 0.6911 - accuracy: 0.5321
Epoch 51/100
804/804 [==============================] - 1s 888us/step - loss: 0.6911 - accuracy: 0.5321
Epoch 52/100
804/804 [==============================] - 1s 925us/step - loss: 0.6911 - accuracy: 0.5321
Epoch 53/100
804/804 [==============================] - 1s 858us/step - loss: 0.6911 - accuracy: 0.5321
Epoch 54/100
804/804 [==============================] - 1s 925us/step - loss: 0.6911 - accuracy: 0.5321
Epoch 55/100
761/804 [===========================>..] - ETA: 0s - loss: 0.6911 - accuracy: 0.5319
Epoch 00055: saving model to checkpoints/weights.55.hdf5
804/804 [==============================] - 1s 949us/step - loss: 0.6911 - accuracy: 0.5321
Epoch 56/100
804/804 [==============================] - 1s 1ms/step - loss: 0.6911 - accuracy: 0.5321
Epoch 57/100
804/804 [==============================] - 1s 896us/step - loss: 0.6911 - accuracy: 0.5321
Epoch 58/100
804/804 [==============================] - 1s 885us/step - loss: 0.6911 - accuracy: 0.5321
Epoch 59/100
804/804 [==============================] - 1s 898us/step - loss: 0.6911 - accuracy: 0.5321
Epoch 60/100
786/804 [============================>.] - ETA: 0s - loss: 0.6911 - accuracy: 0.5319
Epoch 00060: saving model to checkpoints/weights.60.hdf5
804/804 [==============================] - 1s 907us/step - loss: 0.6911 - accuracy: 0.5321
Epoch 61/100
804/804 [==============================] - 1s 882us/step - loss: 0.6911 - accuracy: 0.5321
Epoch 62/100

804/804 [==============================] - 1s 810us/step - loss: 0.6911 - accuracy: 0.5321
Epoch 63/100
804/804 [==============================] - 1s 856us/step - loss: 0.6911 - accuracy: 0.5321
Epoch 64/100
804/804 [==============================] - 1s 838us/step - loss: 0.6911 - accuracy: 0.5321
Epoch 65/100
783/804 [============================>.] - ETA: 0s - loss: 0.6911 - accuracy: 0.5323
Epoch 00065: saving model to checkpoints/weights.65.hdf5
804/804 [==============================] - 1s 848us/step - loss: 0.6911 - accuracy: 0.5321
Epoch 66/100
804/804 [==============================] - 1s 798us/step - loss: 0.6911 - accuracy: 0.5321
Epoch 67/100
804/804 [==============================] - 1s 877us/step - loss: 0.6911 - accuracy: 0.5321
Epoch 68/100
804/804 [==============================] - 1s 783us/step - loss: 0.6911 - accuracy: 0.5321
Epoch 69/100
804/804 [==============================] - 1s 774us/step - loss: 0.6911 - accuracy: 0.5321
Epoch 70/100
751/804 [===========================>..] - ETA: 0s - loss: 0.6911 - accuracy: 0.5325
Epoch 00070: saving model to checkpoints/weights.70.hdf5
804/804 [==============================] - 1s 809us/step - loss: 0.6911 - accuracy: 0.5321
Epoch 71/100
804/804 [==============================] - 1s 875us/step - loss: 0.6911 - accuracy: 0.5321
Epoch 72/100
804/804 [==============================] - 1s 884us/step - loss: 0.6911 - accuracy: 0.5321
Epoch 73/100
804/804 [==============================] - 1s 758us/step - loss: 0.6911 - accuracy: 0.5321
Epoch 74/100
804/804 [==============================] - 1s 776us/step - loss: 0.6911 - accuracy: 0.5321
Epoch 75/100
750/804 [==========================>...] - ETA: 0s - loss: 0.6911 - accuracy: 0.5320
Epoch 00075: saving model to checkpoints/weights.75.hdf5
804/804 [==============================] - 1s 822us/step - loss: 0.6911 - accuracy: 0.5321
Epoch 76/100
804/804 [==============================] - 1s 864us/step - loss: 0.6911 - accuracy: 0.5321
Epoch 77/100
804/804 [==============================] - 1s 805us/step - loss: 0.6911 - accuracy: 0.5321
Epoch 78/100
804/804 [==============================] - 1s 876us/step - loss: 0.6911 - accuracy: 0.5321
Epoch 79/100
804/804 [==============================] - 1s 883us/step - loss: 0.6911 - accuracy: 0.5321
Epoch 80/100
791/804 [============================>.] - ETA: 0s - loss: 0.6911 - accuracy: 0.5321
Epoch 00080: saving model to checkpoints/weights.80.hdf5
804/804 [==============================] - 1s 778us/step - loss: 0.6911 - accuracy: 0.5321
Epoch 81/100
804/804 [==============================] - 1s 887us/step - loss: 0.6911 - accuracy: 0.5321
Epoch 82/100
804/804 [==============================] - 1s 845us/step - loss: 0.6911 - accuracy: 0.5321
Epoch 83/100
804/804 [==============================] - 1s 774us/step - loss: 0.6911 - accuracy: 0.5321
Epoch 84/100
804/804 [==============================] - 1s 764us/step - loss: 0.6911 - accuracy: 0.5321
Epoch 85/100
797/804 [============================>.] - ETA: 0s - loss: 0.6911 - accuracy: 0.5321
Epoch 00085: saving model to checkpoints/weights.85.hdf5
804/804 [==============================] - 1s 766us/step - loss: 0.6911 - accuracy: 0.5321
Epoch 86/100
804/804 [==============================] - 1s 764us/step - loss: 0.6911 - accuracy: 0.5321
Epoch 87/100
804/804 [==============================] - 1s 756us/step - loss: 0.6911 - accuracy: 0.5321
Epoch 88/100
804/804 [==============================] - 1s 861us/step - loss: 0.6911 - accuracy: 0.5321
Epoch 89/100
804/804 [==============================] - 1s 813us/step - loss: 0.6911 - accuracy: 0.5321
Epoch 90/100
804/804 [==============================] - ETA: 0s - loss: 0.6911 - accuracy: 0.5321
Epoch 00090: saving model to checkpoints/weights.90.hdf5
804/804 [==============================] - 1s 761us/step - loss: 0.6911 - accuracy: 0.5321
Epoch 91/100
804/804 [==============================] - 1s 776us/step - loss: 0.6911 - accuracy: 0.5321
Epoch 92/100
804/804 [==============================] - 1s 771us/step - loss: 0.6911 - accuracy: 0.5321
Epoch 93/100
804/804 [==============================] - 1s 842us/step - loss: 0.6911 - accuracy: 0.5321
Epoch 94/100
804/804 [==============================] - 1s 831us/step - loss: 0.6911 - accuracy: 0.5321
Epoch 95/100
751/804 [===========================>..] - ETA: 0s - loss: 0.6911 - accuracy: 0.5318
Epoch 00095: saving model to checkpoints/weights.95.hdf5
804/804 [==============================] - 1s 948us/step - loss: 0.6911 - accuracy: 0.5321
Epoch 96/100
804/804 [==============================] - 1s 998us/step - loss: 0.6911 - accuracy: 0.53210s - loss: 0.6912 - accuracy: 0.53
Epoch 97/100
804/804 [==============================] - 1s 948us/step - loss: 0.6911 - accuracy: 0.5321
Epoch 98/100
804/804 [==============================] - 1s 744us/step - loss: 0.6911 - accuracy: 0.5321
Epoch 99/100
804/804 [==============================] - 1s 875us/step - loss: 0.6911 - accuracy: 0.5321
Epoch 100/100
744/804 [==========================>...] - ETA: 0s - loss: 0.6909 - accuracy: 0.5334
Epoch 00100: saving model to checkpoints/weights.100.hdf5
804/804 [==============================] - 1s 947us/step - loss: 0.6911 - accuracy: 0.5321

In [21]:
# Evaluate the model using the test data
model_loss, model_accuracy = nn.evaluate(X_test_scaled,y_test,verbose=2)
print(f"Loss: {model_loss}, Accuracy: {model_accuracy}")

268/268 - 0s - loss: 1.9397 - accuracy: 0.3165
Loss: 1.939732313156128, Accuracy: 0.3165014684200287

In [22]:
# Export our model to HDF5 file
nn.save("AlphabetSoupCharity_Optimzation(2).h5")